# Generated by Django 6.0.6 on 2026-06-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Road', 'Road'), ('Water', 'Water'), ('Bus', 'Bus'), ('Hospital', 'Hospital'), ('Jobs', 'Jobs'), ('Education', 'Education'), ('Other', 'Other')], max_length=50)),
                ('problem', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.issue')),
            ],
        ),
    ]
