# Generated by Django 6.0.6 on 2026-06-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
